apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app-np
  template:
    metadata:
      labels:
        app: my-app-np
    spec:
      containers:
      - name: my-container
        image: prasad6242/netflix
        ports:
        - containerPort: 4000
---
users:
- name: iam-root-account@kubern8s.eu-west-1.eksctl.io
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      command: aws
      args:
      - eks
      - get-token
      - --cluster-name
      - kubern8s
      - --region
      - eu-west-1

---
apiVersion: v1
kind: Service
metadata:
  name: netflix-svc
  labels:
    app: my-app-np
spec:
  type: LoadBalancer
  ports:
  - port: 4000
    targetPort: 80
    protocol: TCP
    nodePort: 32080
  selector:
    app: my-app-np
